[package]
authors     = { workspace = true }
categories  = ["development-tools"]
description = "Application state management for ChadReview"
edition     = { workspace = true }
keywords    = ["management", "state"]
license     = { workspace = true }
name        = "chadreview_state"
readme      = "README.md"
repository  = { workspace = true }
version     = { workspace = true }

[dependencies]

[features]
default          = []
fail-on-warnings = []
