[package]
authors     = { workspace = true }
categories  = ["development-tools"]
description = "Syntax highlighting for ChadReview"
edition     = { workspace = true }
keywords    = ["highlighting", "syntax"]
license     = { workspace = true }
name        = "chadreview_syntax"
readme      = "README.md"
repository  = { workspace = true }
version     = { workspace = true }

[dependencies]
syntect = { workspace = true, features = [
    "default-syntaxes",
    "default-themes",
    "parsing",
    "regex-onig",
] }

[features]
default          = []
fail-on-warnings = []
